theme: jekyll-theme-cayman
# title: «МЕГАПОЛИС»
# description: Студия танца и фитнеса «МЕГАПОЛИС» в Троицке
lang: ru-RU
markdown: kramdown
sass:
  compress: true
  sass_dir: 'assets/css'

#baseurl: "/"
