theme: jekyll-theme-cayman
title: Студия танца и фитнеса «МЕГАПОЛИС»
description: Студия танца и фитнеса «МЕГАПОЛИС» в Троицке
lang: ru-RU
sass:
  compress: true
  sass_dir: 'assets/css'

baseurl: "/Apelsinka"